### ISSUE TITLE
welcome

### ISSUE THREAD

**Issue by xiaowuming** [marcominetti/webkit-devtools-agent-frontend-profiler#1]
Hello, to find you in the research of'chrome-devtools-frontend', we are currently developing wireless integration platform, including the IOS&Android debugging, performance, test automation, has the interest to join our team to work together?
Alibaba-taobao-ued

**Comment by marcominetti** [comment]
I've sent you a PM with my mail, you can contact me through Hangouts or Skype for a quick text chat.

**Comment by xiaowuming** [comment]
Take so sophisticated chat tools in China.
Know why "front_end / InspectorBackendCommands.js' 404"

2014-12-11 2:26 GMT+08:00 Marco Minetti notifications@github.com:
